version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:4000"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_URL=http://backend:4000/api
    depends_on:
      - backend
