name: Multiple job CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  test:

    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
    - uses: actions/setup-node@v4
      with:
        node-verison: ${{matrix.node-version }}
    - run: npm install
    - run: npm test
